#!/command/with-contenv python3
"""s6 service run script: Launch the Flask WebUI."""

import os

from usbip_lib.constants import WEBUI_INTERNAL_PORT
from usbip_lib.logging_setup import setup_logging

logger = setup_logging("info", name="webui_run")

logger.info(
	"Starting WebUI service on internal port %s...", WEBUI_INTERNAL_PORT
)

os.execvp("python3", ["python3", "/usr/local/bin/webui/app.py"])
